[package]
name = "node-bindgen"
version = "0.1.0"
authors = ["fluvio.io"]
edition = "2018"
description = "tool for generating nodejs binding from rust"
repository = "https://github.com/infinyon/node-bindgen"
readme = "README.md"
license = "Apache-2.0"

[lib]
test = false

[features]
default = ["node"]
node = ["nj-sys","nj-core","nj-derive"]
build = ["nj-build"]

[dependencies]
nj-sys = { path = "nj-sys", optional = true }
nj-core = { path = "nj-core", optional = true  }
nj-build = { path = "nj-build", optional = true }
nj-derive = { path = "nj-derive", optional = true}