[package]
name = "nj-derive"
version = "0.1.0"
authors = ["fluvio.io"]
edition = "2018"

[lib]
proc-macro = true


[dependencies]
proc-macro2 = "1.0"
quote = "1.0.2"
syn = { version = "1.0", features = ["full", "visit-mut"] }
Inflector = "0.11.4"